/* AESCSF v2 Evidence Tracker — runtime configuration
 *
 * In Docker deployment this file is auto-generated by nginx/entrypoint.sh.
 * For local development without Docker, edit the values below directly.
 *
 * Authentication is handled by oauth2-proxy — no clientId/tenantId needed here.
 */
window.__AESCSF_CONFIG__ = {
  storageMode:       "local",   /* "api" for backend persistence, "local" for localStorage */
  apiBaseUrl:        "/api",
  apiAssessmentPath: "/assessment"
};
